import type { Product } from "@/lib/types"

export const footwearProducts: Product[] = [
  {
    id: 1,
    name: "Elegant Stiletto Heels",
    price: 129.99,
    originalPrice: 159.99,
    discount: 20,
    imageUrl: "/placeholder.svg?height=500&width=500",
    category: "heels",
    colors: ["#000000", "#A52A2A", "#D3D3D3"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4,
    reviewCount: 42,
    isNew: true,
    description:
      "These elegant stiletto heels are perfect for formal occasions. The sleek design and comfortable fit make them ideal for long evenings.",
    features: [
      "4-inch heel height",
      "Cushioned insole for comfort",
      "Genuine leather upper",
      "Non-slip rubber sole",
      "Breathable lining",
    ],
  },
  {
    id: 2,
    name: "Casual Leather Flats",
    price: 79.99,
    originalPrice: 0,
    discount: 0,
    imageUrl: "/placeholder.svg?height=500&width=500",
    category: "flats",
    colors: ["#000000", "#8B4513", "#F5F5DC", "#FFFFFF"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 5,
    reviewCount: 87,
    isNew: false,
    description:
      "Our casual leather flats are designed for everyday comfort without sacrificing style. Perfect for work or weekend wear.",
    features: [
      "Genuine soft leather",
      "Memory foam insole",
      "Flexible rubber outsole",
      "Breathable design",
      "Reinforced heel",
    ],
  },
  {
    id: 3,
    name: "Summer Strappy Sandals",
    price: 69.99,
    originalPrice: 89.99,
    discount: 22,
    imageUrl: "/placeholder.svg?height=500&width=500",
    category: "sandals",
    colors: ["#F5F5DC", "#FFD700", "#000000", "#FFFFFF"],
    sizes: ["5", "6", "7", "8", "9"],
    rating: 4,
    reviewCount: 36,
    isNew: true,
    description:
      "These strappy sandals are perfect for summer days and nights. The adjustable straps ensure a perfect fit for any foot shape.",
    features: [
      "Adjustable ankle strap",
      "Cushioned footbed",
      "Lightweight design",
      "Durable outsole",
      "Water-resistant materials",
    ],
  },
  {
    id: 4,
    name: "Classic Ankle Boots",
    price: 149.99,
    originalPrice: 179.99,
    discount: 17,
    imageUrl: "/placeholder.svg?height=500&width=500",
    category: "boots",
    colors: ["#000000", "#8B4513", "#A52A2A"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 5,
    reviewCount: 64,
    isNew: false,
    description:
      "Our classic ankle boots combine timeless style with modern comfort. The versatile design pairs well with jeans, skirts, or dresses.",
    features: [
      "Genuine leather upper",
      "Side zipper for easy on/off",
      "Cushioned insole",
      "Stacked heel (2 inches)",
      "Durable rubber outsole",
    ],
  },
  {
    id: 5,
    name: "Athletic Running Shoes",
    price: 119.99,
    originalPrice: 0,
    discount: 0,
    imageUrl: "/placeholder.svg?height=500&width=500",
    category: "athletic",
    colors: ["#000000", "#FF69B4", "#4169E1", "#FFFFFF"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4,
    reviewCount: 53,
    isNew: true,
    description:
      "Designed for performance and comfort, these running shoes feature advanced cushioning and support for your daily workouts.",
    features: [
      "Breathable mesh upper",
      "Responsive cushioning",
      "Supportive midsole",
      "Durable rubber outsole",
      "Reflective details for visibility",
    ],
  },
  {
    id: 6,
    name: "Elegant Ballet Flats",
    price: 89.99,
    originalPrice: 99.99,
    discount: 10,
    imageUrl: "/placeholder.svg?height=500&width=500",
    category: "flats",
    colors: ["#000000", "#FF69B4", "#F5F5DC", "#A52A2A"],
    sizes: ["5", "6", "7", "8", "9"],
    rating: 4,
    reviewCount: 48,
    isNew: false,
    description:
      "These elegant ballet flats combine classic style with modern comfort. Perfect for work or casual outings.",
    features: [
      "Soft leather upper",
      "Padded insole",
      "Flexible sole",
      "Elasticized topline for secure fit",
      "Breathable lining",
    ],
  },
  {
    id: 7,
    name: "Waterproof Rain Boots",
    price: 99.99,
    originalPrice: 129.99,
    discount: 23,
    imageUrl: "/placeholder.svg?height=500&width=500",
    category: "boots",
    colors: ["#000000", "#FF0000", "#4169E1", "#008000"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    rating: 4,
    reviewCount: 32,
    isNew: false,
    description:
      "Stay dry and stylish with our waterproof rain boots. Perfect for rainy days without compromising on fashion.",
    features: [
      "100% waterproof material",
      "Adjustable buckle",
      "Non-slip sole",
      "Comfortable lining",
      "Pull tab for easy on/off",
    ],
  },
  {
    id: 8,
    name: "Wedge Espadrille Sandals",
    price: 109.99,
    originalPrice: 0,
    discount: 0,
    imageUrl: "/placeholder.svg?height=500&width=500",
    category: "sandals",
    colors: ["#F5F5DC", "#000000", "#8B4513"],
    sizes: ["5", "6", "7", "8", "9"],
    rating: 5,
    reviewCount: 27,
    isNew: true,
    description:
      "Our wedge espadrille sandals offer height and comfort for summer days. The ankle strap provides extra support.",
    features: [
      "3-inch wedge heel",
      "Ankle strap with buckle closure",
      "Jute-wrapped platform",
      "Cushioned footbed",
      "Durable rubber outsole",
    ],
  },
]

