import type { Product } from "@/lib/types"

export const footwearProducts: Product[] = [
    {
      id: 1,
      productId: "ICMJ01MC",
      name: "Panjabi multi colour leather mojari jutti",
      price: 2499,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICMJ01MC.png?height=500&width=500",
      category: "juttis",
      colors: ["#8B0000", "#F5DEB3", "#A0522D"],
      sizes: ["39"],
      rating: 4,
      reviewCount: 12,
      isNew: true,
      description: "Traditional handcrafted mojari jutti with multi-color leather design, perfect for festive occasions.",
      features: [
        "Handcrafted leather upper",
        "Intricate stitching detail",
        "Cushioned insole",
        "Non-slip sole",
        "Durable and breathable lining",
      ],
    },
    {
      id: 2,
      productId: "ICMJ02PW",
      name: "Panjabi handmade embroidery pearl white leather mojari jutti",
      price: 2999,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICMJ02PW.png?height=500&width=500",
      category: "juttis",
      colors: ["#FFFFFF", "#D8BFD8", "#F5F5F5"],
      sizes: ["39"],
      rating: 5,
      reviewCount: 20,
      isNew: true,
      description: "Elegant pearl white jutti with detailed handmade embroidery and soft leather finish.",
      features: [
        "Embroidered pearl patterns",
        "Genuine leather base",
        "Comfortable footbed",
        "Slip-resistant design",
        "Ideal for wedding wear",
      ],
    },
    {
      id: 3,
      productId: "ICMJ03RG",
      name: "Panjabi cherry red gold leather mojari jutti",
      price: 2499,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICMJ03RG.png?height=500&width=500",
      category: "juttis",
      colors: ["#8B0000", "#FFD700", "#FAEBD7"],
      sizes: ["38"],
      rating: 4,
      reviewCount: 15,
      isNew: true,
      description: "Cherry red leather jutti with golden accent, handcrafted with cultural flair.",
      features: [
        "Cherry red & gold tones",
        "Genuine leather craftsmanship",
        "Comfort-fit padding",
        "Fine embroidery details",
        "Durable sole",
      ],
    },
    {
      id: 4,
      productId: "ICMJ04P",
      name: "Panjabi handcraft pink embroidery leather mojari Jutti",
      price: 2699,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICMJ04P.png?height=500&width=500",
      category: "juttis",
      colors: ["#FFC0CB", "#F5F5DC", "#D8BFD8"],
      sizes: ["35"],
      rating: 4,
      reviewCount: 10,
      isNew: true,
      description: "Pink embroidered leather mojari with traditional handcrafting techniques.",
      features: [
        "Soft pink finish",
        "Artisan-stitched embroidery",
        "Leather lining",
        "Breathable and flexible sole",
        "Everyday elegance",
      ],
    },
    {
      id: 5,
      productId: "ICMJ05LG",
      name: "Light green handcraft glass embroidery leather mojari jutti",
      price: 3199,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICMJ05LG.png?height=500&width=500",
      category: "juttis",
      colors: ["#90EE90", "#E0EEE0", "#8FBC8F"],
      sizes: ["36"],
      rating: 5,
      reviewCount: 18,
      isNew: true,
      description: "Refreshing green mojari with handcrafted glass bead embroidery and premium leather.",
      features: [
        "Glass bead detailing",
        "Smooth leather feel",
        "Premium artisan work",
        "Shock-absorbing sole",
        "Versatile ethnic wear",
      ],
    },
    {
      id: 6,
      productId: "ICMJ06WG",
      name: "Hand craft white gold leather mojari jutti",
      price: 3499,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICMJ06WG.png?height=500&width=500",
      category: "juttis",
      colors: ["#FFFFFF", "#FFD700", "#E6E6FA"],
      sizes: ["37"],
      rating: 5,
      reviewCount: 22,
      isNew: true,
      description: "Elegant white mojari with golden hand-crafted embellishments. A regal touch to your outfit.",
      features: [
        "Gold thread accents",
        "Smooth leather base",
        "Supportive footbed",
        "Cultural fusion styling",
        "Perfect for festive events",
      ],
    },
    {
      id: 7,
      productId: "ICS07BWJ",
      name: "Black & white jwellery hand crafted leather universal sandal",
      price: 2999,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICS07BWJ.png?height=500&width=500",
      category: "sandals",
      colors: ["#000000", "#FFFFFF", "#C0C0C0"],
      sizes: ["38"],
      rating: 4,
      reviewCount: 16,
      isNew: true,
      description: "Timeless black and white leather sandal with jewelry-inspired handcrafted details.",
      features: [
        "Ornamental accents",
        "Adjustable leather straps",
        "Comfortable arch support",
        "Everyday premium feel",
        "Jewelry-inspired details",
      ],
    },
    {
      id: 8,
      productId: "ICS08PF",
      name: "Pink hand crafted flower based leather universal sandal",
      price: 3199,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICS08PF.png?height=500&width=500",
      category: "sandals",
      colors: ["#FF69B4", "#FFF0F5", "#FFDAB9"],
      sizes: ["38"],
      rating: 5,
      reviewCount: 19,
      isNew: true,
      description: "Floral-themed pink leather sandal with hand-crafted flower accents for an elegant look.",
      features: [
        "Leather flower designs",
        "Cushioned heel area",
        "Chic and modern fit",
        "Great for casual wear",
        "Slip-on comfort",
      ],
    },
    {
      id: 9,
      productId: "ICS09PS",
      name: "Pearl & shell hand crafted embroidery leather universal sandal",
      price: 2999,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICS09PS.png?height=500&width=500",
      category: "sandals",
      colors: ["#F5F5F5", "#FFFFF0", "#FFE4C4"],
      sizes: ["38"],
      rating: 4,
      reviewCount: 13,
      isNew: true,
      description: "Luxurious leather sandal with pearl and shell embroidery, handcrafted to perfection.",
      features: [
        "Shell + pearl accents",
        "Premium stitching",
        "Beach-to-evening transition",
        "Flexible leather strap",
        "Handcrafted luxury",
      ],
    },
    {
      id: 10,
      productId: "ICS10PJ",
      name: "Pink jwellery hand crafted embroidery leather universal sandal",
      price: 3199,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICS10PJ.png?height=500&width=500",
      category: "sandals",
      colors: ["#FFC0CB", "#F5DEB3", "#F0E68C"],
      sizes: ["38"],
      rating: 5,
      reviewCount: 17,
      isNew: true,
      description: "Handcrafted pink sandals with jewelry-style embroidered motifs on soft leather.",
      features: [
        "Vibrant pink finish",
        "Fine embroidery",
        "Elegant evening wear",
        "Non-slip sole",
        "Lightweight build",
      ],
    },
    {
      id: 11,
      productId: "ICS11WE",
      name: "White hand crafted embroidery leather universal sandal",
      price: 3099,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICS11WE.png?height=500&width=500",
      category: "sandals",
      colors: ["#FFFFFF", "#F8F8FF", "#F5F5F5"],
      sizes: ["38"],
      rating: 4,
      reviewCount: 11,
      isNew: true,
      description: "Subtle and stylish white leather sandals with artisan embroidery. Everyday elegance.",
      features: [
        "Clean white look",
        "Soft strap design",
        "Perfect for formal wear",
        "Embroidered touches",
        "Long-lasting sole",
      ],
    },
    {
      id: 12,
      productId: "ICS12PB",
      name: "Pink hand crafted butterfly leather universal sandal",
      price: 3299,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICS12PB.png?height=500&width=500",
      category: "sandals",
      colors: ["#FFB6C1", "#F5F5F5", "#FFE4E1"],
      sizes: ["38"],
      rating: 5,
      reviewCount: 24,
      isNew: true,
      description: "Cute pink leather sandals featuring handcrafted butterfly art on premium base.",
      features: [
        "Butterfly motif finish",
        "Flexible leather straps",
        "Soft padded insole",
        "Artisanal charm",
        "Perfect for summer strolls",
      ],
    },
    {
      id: 13,
      productId: "ICS13WF",
      name: "White hand crafted flower based embroidery leather universal sandal",
      price: 3099,
      originalPrice: 0,
      discount: 0,
      imageUrl: "/images/ICS13WF.png?height=500&width=500",
      category: "sandals",
      colors: ["#FFFFFF", "#DCDCDC", "#F0FFFF"],
      sizes: ["38"],
      rating: 4,
      reviewCount: 14,
      isNew: true,
      description: "Floral white leather sandals with artisan embroidery. A touch of nature for your feet.",
      features: [
        "Flower-based embroidery",
        "Genuine leather sole",
        "Padded comfort",
        "Elegant and timeless",
        "Secure strap design",
      ],
    },
    {
        id: 14,
        productId: "ICMJ14YL",
        name: "Yellow mirror work handcrafted mojari jutti",
        price: 2899,
        originalPrice: 0,
        discount: 0,
        imageUrl: "/images/ICMJ14YL.png?height=500&width=500",
        category: "juttis",
        colors: ["#FFD700", "#DAA520", "#B8860B"],
        sizes: ["36", "37", "38", "39"],
        rating: 5,
        reviewCount: 25,
        isNew: true,
        description: "Vibrant yellow leather mojari jutti adorned with intricate mirror work and hand embroidery. A festive must-have.",
        features: [
          "Hand-stitched mirror embroidery",
          "Premium yellow leather base",
          "Padded sole for all-day comfort",
          "Durable stitching",
          "Traditional design with a modern flair",
        ],
      },
      {
        id: 15,
        productId: "ICMJ15TL",
        name: "Teal thread embroidered handcrafted mojari jutti",
        price: 2999,
        originalPrice: 0,
        discount: 0,
        imageUrl: "/images/ICMJ15TL.png?height=500&width=500",
        category: "juttis",
        colors: ["#008080", "#40E0D0", "#20B2AA"],
        sizes: ["36", "37", "38", "39"],
        rating: 4,
        reviewCount: 18,
        isNew: true,
        description: "Elegant teal mojari jutti with detailed threadwork embroidery and a sleek handcrafted finish.",
        features: [
          "Teal and turquoise embroidery patterns",
          "Soft leather lining",
          "Cushioned footbed for extra comfort",
          "Unique handcrafted stitching",
          "Ideal for semi-formal and festive wear",
        ],
      }
      
  ];
  
  

